spring.application.name=RepoAPIExracterAgent
# Using OpenAI
#langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
#langchain4j.open-ai.chat-model.model-name=gpt-4o


# Model Configuration
#langchain4j.google-ai.api-key=xxxxxxxxxx
#langchain4j.google-ai.model-name=gemini-2.5-flash

groq.api.key=grok_key_need