spring.application.name=RepoAPIExracterAgent
# Using OpenAI
#langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
#langchain4j.open-ai.chat-model.model-name=gpt-4o


#langchain4j.google-ai.api-key=xxxxxxxxxx
#langchain4j.google-ai.model-name=gemini-2.5-flash

groq.api.key = gsk_xxxxxxxxxxxxxxxxxx
groq.api.modelName= llama-3.3-70b-versatile
groq.api.baseUrl = https://api.groq.com/openai/v1
